"""Upgradation in modals, schemas

Revision ID: 47ecd44ac073
Revises: 9f018d87adca
Create Date: 2026-06-17 11:24:13.126974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47ecd44ac073'
down_revision: Union[str, Sequence[str], None] = '9f018d87adca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist_imports',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('playlist_id', sa.UUID(), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('source_type', sa.String(length=50), server_default='youtube', nullable=False),
    sa.Column('external_playlist_id', sa.String(length=256), nullable=True),
    sa.Column('external_title', sa.String(length=512), nullable=True),
    sa.Column('external_channel', sa.String(length=256), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('total_tracks', sa.Integer(), server_default='0', nullable=False),
    sa.Column('synced_tracks', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed_tracks', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_sync_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_error', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_type IN ('youtube')", name='ck_playlist_import_source_type'),
    sa.CheckConstraint("status IN ('pending','syncing','completed','failed','partial')", name='ck_playlist_import_status'),
    sa.CheckConstraint('synced_tracks >= 0', name='ck_playlist_import_synced_tracks'),
    sa.CheckConstraint('total_tracks >= 0', name='ck_playlist_import_total_tracks'),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'external_playlist_id', name='uq_playlist_import_user_external')
    )
    op.create_index('ix_playlist_imports_next_sync', 'playlist_imports', ['next_sync_at'], unique=False)
    op.create_index('ix_playlist_imports_pending_sync', 'playlist_imports', ['next_sync_at'], unique=False, postgresql_where="auto_sync_enabled = true AND status != 'syncing'")
    op.create_index(op.f('ix_playlist_imports_playlist_id'), 'playlist_imports', ['playlist_id'], unique=False)
    op.create_index('ix_playlist_imports_status', 'playlist_imports', ['status'], unique=False)
    op.create_index('ix_playlist_imports_user_id', 'playlist_imports', ['user_id'], unique=False)
    op.drop_index(op.f('ix_playlists_deleted_at'), table_name='playlists')
    op.add_column('tracks', sa.Column('youtube_url', sa.String(length=2048), nullable=True))
    op.add_column('tracks', sa.Column('thumbnail_url', sa.String(length=2048), nullable=True))
    op.add_column('tracks', sa.Column('channel_name', sa.String(length=255), nullable=True))
    op.add_column('tracks', sa.Column('release_year', sa.Integer(), nullable=True))
    op.add_column('tracks', sa.Column('language', sa.String(length=50), nullable=True))
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.create_index('ix_user_preferences_user_id', 'user_preferences', ['user_id'], unique=False)
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.drop_index('ix_user_preferences_user_id', table_name='user_preferences')
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.drop_column('tracks', 'language')
    op.drop_column('tracks', 'release_year')
    op.drop_column('tracks', 'channel_name')
    op.drop_column('tracks', 'thumbnail_url')
    op.drop_column('tracks', 'youtube_url')
    op.create_index(op.f('ix_playlists_deleted_at'), 'playlists', ['deleted_at'], unique=False)
    op.drop_index('ix_playlist_imports_user_id', table_name='playlist_imports')
    op.drop_index('ix_playlist_imports_status', table_name='playlist_imports')
    op.drop_index(op.f('ix_playlist_imports_playlist_id'), table_name='playlist_imports')
    op.drop_index('ix_playlist_imports_pending_sync', table_name='playlist_imports', postgresql_where="auto_sync_enabled = true AND status != 'syncing'")
    op.drop_index('ix_playlist_imports_next_sync', table_name='playlist_imports')
    op.drop_table('playlist_imports')
    # ### end Alembic commands ###
