"""add auth models

Revision ID: 9f018d87adca
Revises: 
Create Date: 2026-06-17 02:43:38.835870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f018d87adca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracks',
    sa.Column('external_id', sa.String(length=256), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('artist', sa.String(length=512), nullable=False),
    sa.Column('album', sa.String(length=512), nullable=True),
    sa.Column('album_art_url', sa.String(length=2048), nullable=True),
    sa.Column('preview_url', sa.String(length=2048), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('tempo_bpm', sa.Float(), nullable=True),
    sa.Column('valence', sa.Float(), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('danceability', sa.Float(), nullable=True),
    sa.Column('speechiness', sa.Float(), nullable=True),
    sa.Column('acousticness', sa.Float(), nullable=True),
    sa.Column('mood_tags', postgresql.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("provider IN ('spotify','apple_music','youtube_music')", name='ck_track_provider'),
    sa.CheckConstraint('danceability >= 0.0 AND danceability <= 1.0 OR danceability IS NULL', name='ck_track_danceability'),
    sa.CheckConstraint('duration_ms > 0 OR duration_ms IS NULL', name='ck_track_duration_positive'),
    sa.CheckConstraint('energy >= 0.0 AND energy <= 1.0 OR energy IS NULL', name='ck_track_energy'),
    sa.CheckConstraint('valence >= 0.0 AND valence <= 1.0 OR valence IS NULL', name='ck_track_valence'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id', name='uq_track_provider_external')
    )
    op.create_index('ix_tracks_artist', 'tracks', ['artist'], unique=False)
    op.create_index('ix_tracks_mood_tags', 'tracks', ['mood_tags'], unique=False, postgresql_using='gin')
    op.create_index('ix_tracks_provider_external', 'tracks', ['provider', 'external_id'], unique=False)
    op.create_index('ix_tracks_valence_energy', 'tracks', ['valence', 'energy'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=2048), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_email_active', 'users', ['email'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action_date', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_logs_request_id', 'audit_logs', ['request_id'], unique=False)
    op.create_index('ix_audit_logs_user_date', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('auth_providers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_user_id', sa.String(length=256), nullable=False),
    sa.Column('access_token_enc', sa.String(length=2048), nullable=True),
    sa.Column('refresh_token_enc', sa.String(length=2048), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('provider_email', sa.String(length=320), nullable=True),
    sa.Column('provider_display_name', sa.String(length=256), nullable=True),
    sa.Column('provider_avatar_url', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("provider IN ('email', 'google', 'apple')", name='ck_auth_provider_name'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_auth_provider_pid')
    )
    op.create_index('ix_auth_providers_provider_uid', 'auth_providers', ['provider', 'provider_user_id'], unique=False)
    op.create_index(op.f('ix_auth_providers_user_id'), 'auth_providers', ['user_id'], unique=False)
    op.create_index('ix_auth_providers_user_provider', 'auth_providers', ['user_id', 'provider'], unique=False)
    op.create_table('emotion_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('total_snapshots', sa.Integer(), server_default='0', nullable=False),
    sa.Column('dominant_emotion', sa.String(length=16), nullable=True),
    sa.Column('avg_confidence', sa.Float(), nullable=True),
    sa.Column('mood_profile', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("dominant_emotion IN ('happy','sad','angry','fear','disgust','surprise','neutral') OR dominant_emotion IS NULL", name='ck_emotion_session_emotion'),
    sa.CheckConstraint("status IN ('active','completed','failed','cancelled')", name='ck_emotion_session_status'),
    sa.CheckConstraint('avg_confidence >= 0.0 AND avg_confidence <= 1.0 OR avg_confidence IS NULL', name='ck_emotion_session_confidence'),
    sa.CheckConstraint('total_snapshots >= 0', name='ck_emotion_session_snapshot_count'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_emotion_sessions_active', 'emotion_sessions', ['user_id'], unique=False, postgresql_where="status = 'active'")
    op.create_index('ix_emotion_sessions_started_at', 'emotion_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_emotion_sessions_user_id'), 'emotion_sessions', ['user_id'], unique=False)
    op.create_index('ix_emotion_sessions_user_started', 'emotion_sessions', ['user_id', 'started_at'], unique=False)
    op.create_index('ix_emotion_sessions_user_status', 'emotion_sessions', ['user_id', 'status'], unique=False)
    op.create_table('playlists',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('emotion_context', sa.String(length=32), nullable=True),
    sa.Column('is_auto_generated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('cover_image_url', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlists_deleted_at'), 'playlists', ['deleted_at'], unique=False)
    op.create_index('ix_playlists_emotion_context', 'playlists', ['emotion_context'], unique=False)
    op.create_index('ix_playlists_user_active', 'playlists', ['user_id'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index(op.f('ix_playlists_user_id'), 'playlists', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=256), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_hash', name='uq_sessions_token_hash')
    )
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_refresh_token_hash'), 'sessions', ['refresh_token_hash'], unique=True)
    op.create_index('ix_sessions_revoked_at', 'sessions', ['revoked_at'], unique=False)
    op.create_index('ix_sessions_user_active', 'sessions', ['user_id'], unique=False, postgresql_where='revoked_at IS NULL')
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('user_music_interactions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('interaction_type', sa.String(length=32), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('play_pct', sa.Integer(), nullable=True),
    sa.Column('emotion_context', sa.String(length=16), nullable=True),
    sa.Column('interacted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("interaction_type IN ('play','skip','like','dislike','add_to_playlist','share')", name='ck_interaction_type'),
    sa.CheckConstraint('play_pct >= 0 AND play_pct <= 100 OR play_pct IS NULL', name='ck_interaction_play_pct'),
    sa.CheckConstraint('rating >= 1 AND rating <= 5 OR rating IS NULL', name='ck_interaction_rating'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_interactions_interacted_at', 'user_music_interactions', ['interacted_at'], unique=False)
    op.create_index('ix_interactions_track_type', 'user_music_interactions', ['track_id', 'interaction_type'], unique=False)
    op.create_index('ix_interactions_user_track', 'user_music_interactions', ['user_id', 'track_id'], unique=False)
    op.create_index('ix_interactions_user_type', 'user_music_interactions', ['user_id', 'interaction_type'], unique=False)
    op.create_index(op.f('ix_user_music_interactions_interacted_at'), 'user_music_interactions', ['interacted_at'], unique=False)
    op.create_index(op.f('ix_user_music_interactions_track_id'), 'user_music_interactions', ['track_id'], unique=False)
    op.create_index(op.f('ix_user_music_interactions_user_id'), 'user_music_interactions', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('preferred_genres', postgresql.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('blocked_genres', postgresql.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('blocked_artists', postgresql.ARRAY(sa.String(length=256)), nullable=True),
    sa.Column('music_provider', sa.String(length=32), server_default='spotify', nullable=False),
    sa.Column('auto_play', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('allow_frame_storage', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('show_emotion_overlay', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('confidence_threshold', sa.Float(), server_default='0.60', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_preferences_user')
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.create_table('emotion_snapshots',
    sa.Column('emotion_session_id', sa.UUID(), nullable=False),
    sa.Column('dominant_emotion', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('face_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('frame_s3_key', sa.String(length=512), nullable=True),
    sa.Column('raw_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_version', sa.String(length=32), nullable=True),
    sa.Column('processing_ms', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("dominant_emotion IN ('happy','sad','angry','fear','disgust','surprise','neutral')", name='ck_snapshot_dominant_emotion'),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='ck_snapshot_confidence_range'),
    sa.CheckConstraint('face_count >= 0', name='ck_snapshot_face_count'),
    sa.ForeignKeyConstraint(['emotion_session_id'], ['emotion_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emotion_snapshots_captured_at'), 'emotion_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_emotion_snapshots_emotion_session_id'), 'emotion_snapshots', ['emotion_session_id'], unique=False)
    op.create_index('ix_snapshot_captured_at', 'emotion_snapshots', ['captured_at'], unique=False)
    op.create_index('ix_snapshot_dominant_emotion', 'emotion_snapshots', ['dominant_emotion'], unique=False)
    op.create_index('ix_snapshot_session_time', 'emotion_snapshots', ['emotion_session_id', 'captured_at'], unique=False)
    op.create_table('playlist_tracks',
    sa.Column('playlist_id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('position >= 1', name='ck_playlist_track_position'),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('playlist_id', 'position', name='uq_playlist_track_position'),
    sa.UniqueConstraint('playlist_id', 'track_id', name='uq_playlist_track')
    )
    op.create_index('ix_playlist_tracks_playlist_id', 'playlist_tracks', ['playlist_id'], unique=False)
    op.create_index(op.f('ix_playlist_tracks_track_id'), 'playlist_tracks', ['track_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('emotion_session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mood_profile', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('track_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_feedback', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='ck_recommendation_confidence'),
    sa.CheckConstraint('track_count >= 0', name='ck_recommendation_track_count'),
    sa.CheckConstraint('user_feedback IN (-1, 1) OR user_feedback IS NULL', name='ck_recommendation_user_feedback'),
    sa.ForeignKeyConstraint(['emotion_session_id'], ['emotion_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('emotion_session_id', name='uq_recommendation_session')
    )
    op.create_index('ix_recommendation_mood_profile', 'recommendations', ['mood_profile'], unique=False)
    op.create_index('ix_recommendation_user_generated', 'recommendations', ['user_id', 'generated_at'], unique=False)
    op.create_index(op.f('ix_recommendations_emotion_session_id'), 'recommendations', ['emotion_session_id'], unique=True)
    op.create_index(op.f('ix_recommendations_user_id'), 'recommendations', ['user_id'], unique=False)
    op.create_table('recommendation_tracks',
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('position >= 1', name='ck_rec_track_position'),
    sa.CheckConstraint('relevance_score >= 0.0 AND relevance_score <= 1.0', name='ck_rec_track_relevance'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recommendation_id', 'position', name='uq_rec_track_position'),
    sa.UniqueConstraint('recommendation_id', 'track_id', name='uq_rec_track_unique')
    )
    op.create_index('ix_rec_tracks_recommendation_id', 'recommendation_tracks', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_recommendation_tracks_recommendation_id'), 'recommendation_tracks', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_recommendation_tracks_track_id'), 'recommendation_tracks', ['track_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_tracks_track_id'), table_name='recommendation_tracks')
    op.drop_index(op.f('ix_recommendation_tracks_recommendation_id'), table_name='recommendation_tracks')
    op.drop_index('ix_rec_tracks_recommendation_id', table_name='recommendation_tracks')
    op.drop_table('recommendation_tracks')
    op.drop_index(op.f('ix_recommendations_user_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_emotion_session_id'), table_name='recommendations')
    op.drop_index('ix_recommendation_user_generated', table_name='recommendations')
    op.drop_index('ix_recommendation_mood_profile', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_playlist_tracks_track_id'), table_name='playlist_tracks')
    op.drop_index('ix_playlist_tracks_playlist_id', table_name='playlist_tracks')
    op.drop_table('playlist_tracks')
    op.drop_index('ix_snapshot_session_time', table_name='emotion_snapshots')
    op.drop_index('ix_snapshot_dominant_emotion', table_name='emotion_snapshots')
    op.drop_index('ix_snapshot_captured_at', table_name='emotion_snapshots')
    op.drop_index(op.f('ix_emotion_snapshots_emotion_session_id'), table_name='emotion_snapshots')
    op.drop_index(op.f('ix_emotion_snapshots_captured_at'), table_name='emotion_snapshots')
    op.drop_table('emotion_snapshots')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_user_music_interactions_user_id'), table_name='user_music_interactions')
    op.drop_index(op.f('ix_user_music_interactions_track_id'), table_name='user_music_interactions')
    op.drop_index(op.f('ix_user_music_interactions_interacted_at'), table_name='user_music_interactions')
    op.drop_index('ix_interactions_user_type', table_name='user_music_interactions')
    op.drop_index('ix_interactions_user_track', table_name='user_music_interactions')
    op.drop_index('ix_interactions_track_type', table_name='user_music_interactions')
    op.drop_index('ix_interactions_interacted_at', table_name='user_music_interactions')
    op.drop_table('user_music_interactions')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index('ix_sessions_user_active', table_name='sessions', postgresql_where='revoked_at IS NULL')
    op.drop_index('ix_sessions_revoked_at', table_name='sessions')
    op.drop_index(op.f('ix_sessions_refresh_token_hash'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_playlists_user_id'), table_name='playlists')
    op.drop_index('ix_playlists_user_active', table_name='playlists', postgresql_where='deleted_at IS NULL')
    op.drop_index('ix_playlists_emotion_context', table_name='playlists')
    op.drop_index(op.f('ix_playlists_deleted_at'), table_name='playlists')
    op.drop_table('playlists')
    op.drop_index('ix_emotion_sessions_user_status', table_name='emotion_sessions')
    op.drop_index('ix_emotion_sessions_user_started', table_name='emotion_sessions')
    op.drop_index(op.f('ix_emotion_sessions_user_id'), table_name='emotion_sessions')
    op.drop_index('ix_emotion_sessions_started_at', table_name='emotion_sessions')
    op.drop_index('ix_emotion_sessions_active', table_name='emotion_sessions', postgresql_where="status = 'active'")
    op.drop_table('emotion_sessions')
    op.drop_index('ix_auth_providers_user_provider', table_name='auth_providers')
    op.drop_index(op.f('ix_auth_providers_user_id'), table_name='auth_providers')
    op.drop_index('ix_auth_providers_provider_uid', table_name='auth_providers')
    op.drop_table('auth_providers')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_user_date', table_name='audit_logs')
    op.drop_index('ix_audit_logs_request_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_date', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_index('ix_users_email_active', table_name='users', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_tracks_valence_energy', table_name='tracks')
    op.drop_index('ix_tracks_provider_external', table_name='tracks')
    op.drop_index('ix_tracks_mood_tags', table_name='tracks', postgresql_using='gin')
    op.drop_index('ix_tracks_artist', table_name='tracks')
    op.drop_table('tracks')
    # ### end Alembic commands ###
